# Generated by Django 3.0.7 on 2020-09-27 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sn0', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('instagram_username', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('Add_Field_Name', models.CharField(blank=True, max_length=255)),
                ('Add_Field_Name_2', models.CharField(blank=True, max_length=255)),
                ('Add_Field_Name_3', models.CharField(blank=True, max_length=255)),
                ('Add_Field_Name_4', models.CharField(blank=True, max_length=255)),
                ('Field_Link', models.CharField(blank=True, max_length=255)),
                ('Field_Link_2', models.CharField(blank=True, max_length=255)),
                ('Field_Link_3', models.CharField(blank=True, max_length=255)),
                ('Field_Link_4', models.CharField(blank=True, max_length=255)),
                ('quora', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(max_length=130)),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
